apiVersion: apps/v1
kind: Deployment

metadata:
  name: client-deployment

spec:
  replicas: 3

  selector:
    matchLabels:
      server: client-deployment

  template:
    metadata:
      labels:
        server: client-deployment
    spec:
      containers:
        - name: split-client
          image: jonathanleedev/split-client:latest
          ports:
            - containerPort: 4200
  # TODO add other environment variables and work out secrets
